language: python
os:
  - linux
  - osx
  - windows
python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - sudo apt-get update
  - pip install -r requirements.txt
  - python setup.py install
script:
  - python scripts/run_tests.py

after_success:
  - codecov