language: python
os:
  - linux
python:
  - "2.7"
cache: pip
install:
  - sudo apt-get update
  - pip install -r requirements.txt
  - python setup.py install
script:
  - python scripts/run_tests.py

after_success:
  - codecov